feat: 프로젝트 설정
f-lab-edu/flutter-withu pull request #1
Opened 2024-09-28 08:25 UTC by Younggun-Kim

## 변경사항

1. BLoC 패턴, 클린 아키텍처를 고려한 프로젝트 구조 설정

- BLoC 과 클린 아키텍처 구조를 이용해 확장성 있게 프로젝트를 진행하는 것을 목표로 하고 있습니다.

2. ReadME 초안 작성

- ReadME의 주요 기능에 기존 기능을 Drill Down 하여 작성하였습니다.

2024-09-29 12:37 UTC, abdul0986 requested changes
몇 가지 수정 요청건 반영 부탁드립니다.

2024-09-29 12:37 UTC, abdul0986 commented on lib/core/utils/utils.dart
> +export 'injections.dart';
EOL (End of Line) 넣어주세요

2024-09-30 09:56 UTC, Younggun-Kim commented on lib/core/utils/utils.dart
> +export 'injections.dart';
flutter_lint에 EOL 규칙을 추가해서 프로젝트 전반적으로 적용될 수 있게 수정했습니다!

2024-10-06 12:31 UTC, abdul0986 approved these changes
LGTM

2024-10-06 13:21 UTC, merged