[#5] 공고 마감 기능 구현
f-lab-edu/flutter-withu pull request #11
Opened 2024-10-22 17:23 UTC by Younggun-Kim

### 변경 사항
* 공고 마감 기능 구현
* 공고 상세 화면에 더보기 팝업 추가
* `DescriptionBottomSheet` 추가
* `DetailBottomSheetFactory`를 통해 공고 상세 화면에 필요한 `DescriptionBottomSheet` 를 Factory 패턴으로 생성

### 질문 사항
* `DetailBottomSheetFactory`를 적용한 이유는 `DetailBottomSheetType` 의 각 타입에 따라 맞는 Bottom Sheet를 노출하기 위함입니다.
* 최초 코드에서는 `switch-case` 문으로 작성하였는데 이럴 경우 OCP 원칙을 준수하지 않는다는 말씀이 기억나서, Factory 패턴을 적용해 봤습니다.
* 적용한 코드가 OCP 원칙을 잘 준수하는지 궁금합니다.

### Screenshot
[Screen_recording_20241023_022043.webm](https://github.com/user-attachments/assets/df39681d-31e0-4fde-b063-0a025b01f824)

close #5

2024-10-28 11:20 UTC, abdul0986 requested changes
피드백 확인 부탁드립니다.

2024-10-28 11:20 UTC, abdul0986 commented on lib/feature/job_posting/domain/usecases/usecases_impl.dart
> +    }
enum 타입이므로, null을 가급적 사용하지 않을 수 있도록 null에 대응하는 항목을 정의해서 사용하면 좋을 것 같습니다.

2024-10-28 11:20 UTC, abdul0986 commented on lib/feature/job_posting/domain/usecases/usecases_impl.dart
> +    if (entity.hasTravelTime && entity.isTravelTimePaid == null) {
if 에 해당하는 조건이 복잡해진다면 조건 부분만 별도로 함수로 정의해서 사용하는 것은 어떨까요?

2024-10-29 18:31 UTC, Younggun-Kim commented on lib/feature/job_posting/domain/usecases/usecases_impl.dart
> +    }
enum 타입에 none 값을 추가하여 null을 대체하였습니다!

2024-10-29 18:33 UTC, Younggun-Kim commented on lib/feature/job_posting/domain/usecases/usecases_impl.dart
> +    if (entity.hasTravelTime && entity.isTravelTimePaid == null) {
유효성 검사를 `JobPostingRequestEntity`로 옮기고,
`job_posting_request_entity.validator.dart` 서브 파일을 생성해서
해당 파일에서 수행하도록 수정하였습니다.
그리고 if 조건에 해당하는 조건식은 getter 변수를
이용하는 방식으로 변경해 봤습니다!

2024-10-29 18:42 UTC, Younggun-Kim reviewed
코멘트 달아주신 부분 수정 완료했습니다!

2024-10-29 18:44 UTC, Younggun-Kim commented on lib/core/utils/validation/validation_result.dart
> +}
유효성 검사 시, null을 반환하는 대신 ValidationResult로 관리하도록 변경해 봤습니다!

2024-10-29 18:44 UTC, Younggun-Kim commented on lib/feature/job_posting/domain/usecases/usecases_impl.dart
> +  }
기존의 `null` 값으로 조건 검사 하던 코드를
추가한 `ValidationResult` 를 이용해 변경했습니다.

2024-11-03 09:52 UTC, abdul0986 approved these changes
LGTM

2024-11-03 13:32 UTC, merged