[#6] 공고 삭제 기능 구현
f-lab-edu/flutter-withu pull request #13
Opened 2024-10-23 23:13 UTC by Younggun-Kim

### 변경사항
* 공고 삭제 기능 구현
* 공용 삭제 응답 모델인 `DeleteResponseDto` 추가

### Screenshot
[공고_삭제_영상.webm](https://github.com/user-attachments/assets/59ec34c1-c5a2-4c3b-89a8-e0953607b160)

### Issues
close #6

2024-10-28 11:27 UTC, abdul0986 requested changes
피드백 확인 부탁드립니다.

2024-10-28 11:27 UTC, abdul0986 commented on lib/feature/job_posting/domain/usecases/usecases_impl.dart
> +        await repository.deleteJobPosting(jobPostingId: jobPostingId);
```suggestion
        await repository.delete(id: jobPostingId);
```

2024-10-30 14:52 UTC, Younggun-Kim commented on lib/feature/job_posting/domain/usecases/usecases_impl.dart
> +        await repository.deleteJobPosting(jobPostingId: jobPostingId);
#11  PR 수정하면서 같이 반영해 푸시했습니다!
 `jobPostingRepo.delete()`로 사용할 수 있게 변경했습니다!

2024-11-10 12:17 UTC, abdul0986 approved these changes
LGTM

2024-11-10 15:51 UTC, merged