Feature/ 공고 목록 화면 추가
f-lab-edu/flutter-withu pull request #2
Opened 2024-10-05 14:26 UTC by Younggun-Kim

### 변경사항
1. 공고사항 목록 추가 - `job_posting `으로 이름을 지었습니다.
2. `flutter_gen`  라이브러리로 Color 리소스 제너레이팅 추가
3. `easy_localization` 추가 및 StringRes Enum으로 쉽게 쓸 수 있게 추가
4. TextTheme 추가

### 이슈 사항
1. API 서버가 아직 준비가 안되어서 임시로 `List.generate` 로 생성했습니다.

### 질문 사항
1. 코드가 아키텍처의 기능별로 잘 나뉘었는지, 보기 좋게 코딩했는지 궁금합니다.
2. 커밋의 내용이 작업 내용을 잘 반영하고 있는지 궁금합니다.
3. "공고 목록" feature를 개발해 봤는데, 멘토님이 생각하신 내용으로 제가 잘 했는지, 부족한 점에 대해서 궁금합니다.

### Screenshot

Uploading 공고관리목록_동작_화면 (1).mp4

https://github.com/user-attachments/assets/9fc09c37-6dac-4d0c-950f-56bb9feb0708

…

2024-10-06 13:09 UTC, abdul0986 requested changes
피드백 확인 부탁드립니다~!!!!

2024-10-06 13:09 UTC, abdul0986 commented on lib/feature/job_posting/domain/usecases/usecases.dart
> +              max: dto.max,
이 처리에 대한 책임을 `JobPostingEntity` 에 맡기는 건 어떨까요?

2024-10-06 13:09 UTC, abdul0986 commented on lib/core/type/job_posting_status_type.dart
이 코드를 OCP 룰을 준수하는 방향으로 리팩토링할 수 있을지 고민해주세요

2024-10-08 18:36 UTC, Younggun-Kim commented on lib/core/type/job_posting_status_type.dart
기존의 Extension에서 switch-case문 방식의 경우 Enum 타입값이 추가될 때마다  OCP 룰이 깨진다고 생각했습니다.
그래서 `mixin I10nKeyProvider {}` 를 추가하여 Enum 타입이 추가되어도 문제없는 방식으로 수정해보았습니다.

2024-10-08 18:40 UTC, Younggun-Kim commented on lib/feature/job_posting/domain/usecases/usecases.dart
> +              max: dto.max,
JobPostingEntity에서 Factory 패턴을 활용해
`JobPostingEntity.fromModel(JobPostingModel model)` 이렇게 model -> entity로
변경하는 방식으로 적용해 봤습니다!

2024-10-08 18:45 UTC, Younggun-Kim commented on lib/feature/job_posting/data/data_sources/remote/job_posting_api.dart
> +        ),
우선 프로젝트의 환경을 간단하게 `prod`, `dev`로 구분을 하고,
`prod` - `JobPostingApiImpl`, 
`dev` - `JobpostingMockApi`,
각 환경마다 주입받는 값을 다르게 구현했습니다.

그리고 Mock Api는 기존처럼 `List.generate`을 이용하지만, `http_mock_adapter` 라이브러리를 추가해
현재 프로젝트에서 사용중인 `dio` http 라이브러이를 mocking해서 사용하는 방식으로 구현해 봤습니다!

2024-10-08 18:45 UTC, Younggun-Kim commented on assets/translations/en.json
말씀하신 `pre-commit hook`을 적용하여 eol 수정 완료했습니다!

2024-10-08 18:51 UTC, Younggun-Kim commented on lib/feature/job_posting/data/data_sources/remote/job_posting_api.dart
> +      return null;
`null` -> `[] ` 우선 빈 객체로 반환하는 형식으로 변경했습니다.
다트의 경우 null safety를 강조하고 있기에 null을 남용하는 것보다 더 안전하다는 생각이 들고,
사용하는 데 있어서도 List를 다루는데 일관성이 있다는 생각이 듭니다.

현재는 `[]` 빈 객체를 반환하도록 하였지만, 
추후 Result 패턴이나 다른 좋은 방식으로 변경할 수 있게 생각해 보겠습니다.

2024-10-11 01:45 UTC, abdul0986 requested changes
깔끔하게 정리 잘 하셨네요 
코멘트 남긴 하나만 확인해주시면 Approve 하겠습니다. :)

2024-10-11 07:54 UTC, Younggun-Kim commented on assets/translations/en.json
en.json 파일의 경우 l10n 동작 테스트용으로 보려고 해서
삭제했습니다!
PR 올릴 때 테스트 관련 정보들은 삭제하도록 더 신경 쓰겠습니다!

2024-10-13 08:26 UTC, abdul0986 approved these changes
LGTM

2024-10-13 11:09 UTC, merged