공고 목록 리팩토링
f-lab-edu/flutter-withu pull request #20
Opened 2024-10-28 09:38 UTC by Younggun-Kim

### 공고 목록 기능 리팩토링
* `BaseBloc` 추가
  *  앱 각 화면마다 공통적으로 필요한 status 정의 (ex, initial, loading, refresh)
* `JobPostingsBloc`에 `BaseBloc` 적용
* Bloc State에 `@freezed` 적용 및 `@Default` 어노테이션 적용
  *  기존 코드에서 불필요한 코드 삭제 ex) `copyWith`, `Equatable` 
* 공고 목록 Dto에 `PaginationDto`  적용

2024-11-10 12:52 UTC, abdul0986 commented on lib/feature/job_posting/domain/entities/list/job_postings_entity.dart
> +  final List<JobPostingsItemEntity> list;
`list`가 모호하게 의미전달될 수 있습니다. `jobPostings` 또는 `jobPostingItems` 정도로 구체화해보는 것은 어떨까요?

2024-11-10 12:53 UTC, abdul0986 requested changes
피드백 확인 부탁드립니다.

2024-11-10 18:56 UTC, Younggun-Kim commented on lib/feature/job_posting/domain/entities/list/job_postings_entity.dart
> +  final List<JobPostingsItemEntity> list;
`jobPostingItems`로 변경했습니다!

2024-11-17 11:47 UTC, abdul0986 approved these changes
LGTM

2024-11-20 05:56 UTC, merged